name: Spanner DDL Deploy
on:
  workflow_dispatch:
    inputs:
      instnace:
        type: choice
        description: 'Select Instance'  
        required: true
        default: 'demo-instance'
        options:
          - 'demo-instance'
          - 'my-instance'

      database:
        type: choice
        description: 'Select Database'  
        required: true
        default: 'demo-database'
        options:
          - 'demo-database'
          - 'my-database'

      

permissions:
  id-token: write 
  contents: read

jobs:
  spanner-ddl-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploy Spanner DDL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      - name: Run Python Script to Create Tables
        run: |
           cd scripts
           pip install -r requirements.txt
           python create_spanner_tables.py
          

