name: Spanner DDL Deploy
on:
  push:
   branches: 
    - feature*

  workflow_dispatch:

jobs:
  spanner-ddl-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploy DDL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0 

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      - name: Run Python
        run: |
           cd scripts
           pwd
           ls
           set -x
           git diff --unified=0 HEAD ../sql/db.sql
           #pip install -r requirements.txt
           python db.py
          

